Get 418 to work
ksabbak/JavaServer pull request #4
Opened 2018-06-06 14:57 UTC by ksabbak

You know when you take forever to write an email and then you expect the email to be better and better the longer it takes you to send it in order to justify the length of time it took you to get back to the person, but the email does not improve and it is still just an acceptable email and you feel like you should have sent it sooner but it's too late now? That's how I feel about this particular PR.

Also, suggestions on what to do with the switch/conditionals that are likely going to keep multiplying would be appreciated.

2018-06-06 16:14 UTC, BWoodfork commented on src/main/java/com/ksabbak/javaserver/app/controller/ControllerFactory.java
> +//public String getTypeOfDayWithSwitchStatement(String dayOfWeekArg) {
Dead code

2018-06-06 17:22 UTC, ksabbak commented on src/main/java/com/ksabbak/javaserver/app/controller/ControllerFactory.java
> +//public String getTypeOfDayWithSwitchStatement(String dayOfWeekArg) {
Whoops, thanks!

2018-06-06 21:25 UTC, hnlee requested changes
You don't need to refactor right away on the comment about my finding the `Responder` hard to follow or the comment on the routes, but keep them in mind as the design of your server evolves.

Other than that `Responder` class, it's very clean and readable, and the unit tests are looking good!

2018-06-06 21:25 UTC, hnlee commented on src/main/java/com/ksabbak/javaserver/app/Responder.java
> +        if (Arrays.asList(methods).contains(HTTPMethod.GET)){
Should this be `HTTPMethod.HEAD`?

2018-06-06 21:25 UTC, hnlee commented on src/main/java/com/ksabbak/javaserver/app/Responder.java
> +    }
I found this a bit hard to follow.

What about if the controller returned an object that contained both a status and a body?

2018-06-06 21:25 UTC, hnlee commented on src/main/java/com/ksabbak/javaserver/app/Routes.java
> +        map.put("/", new Object[]{HTTPMethod.GET, HTTPMethod.HEAD});
I wonder if it would be easier if you had a separate route for every method and path combination. You might not want GET / to return the same response as HEAD /.

2018-06-06 21:25 UTC, hnlee commented on src/main/java/com/ksabbak/javaserver/app/Responder.java
> +        if (Arrays.asList(methods).contains(HTTPMethod.GET)){
Maybe store them as a `List` to begin with? Is there an advantage to storing as an `Array`?

2018-06-06 21:25 UTC, hnlee commented on src/main/java/com/ksabbak/javaserver/app/Routes.java
> +    private static Map<String, Object[]> initMap() {
Why is it a generic `Object[]` instead of an `HTTPMethod[]`?

2018-06-06 21:40 UTC, ksabbak commented on src/main/java/com/ksabbak/javaserver/app/Responder.java
> +        if (Arrays.asList(methods).contains(HTTPMethod.GET)){
Yes it should! Thanks for catching that.

2018-06-06 21:42 UTC, ksabbak commented on src/main/java/com/ksabbak/javaserver/app/Responder.java
> +    }
Realized today that that's where this is headed, that refactor will happen when I get to Simple OPTION. I'm glad that will also increase clarity as well as like, make things work better.

2018-06-06 22:01 UTC, ksabbak commented on src/main/java/com/ksabbak/javaserver/app/Routes.java
> +        map.put("/", new Object[]{HTTPMethod.GET, HTTPMethod.HEAD});
I'd love to pick your brain about this a bit more next week. Can we set aside some time to chat?

2018-06-06 22:11 UTC, ksabbak commented on src/main/java/com/ksabbak/javaserver/app/Responder.java
> +        if (Arrays.asList(methods).contains(HTTPMethod.GET)){
Probably not. I'll double check, but I think it was just a Java fail. >.>

2018-06-06 22:12 UTC, ksabbak commented on src/main/java/com/ksabbak/javaserver/app/Routes.java
> +    private static Map<String, Object[]> initMap() {
Another Java fail! I'll fix this too. Thanks!

2018-06-07 18:54 UTC, hnlee commented on src/main/java/com/ksabbak/javaserver/app/Routes.java
> +        map.put("/", new Object[]{HTTPMethod.GET, HTTPMethod.HEAD});
Sure, let's set up a time to either pair or do a Slack call.

2018-06-08 16:11 UTC, merged